# Generated by Django 3.1.5 on 2021-01-21 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Особенности курса')),
            ],
            options={
                'verbose_name': 'Формат курса',
                'verbose_name_plural': 'Форматы курсов',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Особенности курса')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Иконка категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='in_menu',
            field=models.BooleanField(default=True, verbose_name='Добавляем ли в меню?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(max_length=255)),
                ('in_menu', models.BooleanField(default=True, verbose_name='Добавляем ли в меню?')),
                ('order', models.IntegerField(default=1)),
                ('content', models.TextField(blank=True)),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Иконка подкатегории')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название школы')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Логотип')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на школу')),
                ('categories', models.ManyToManyField(to='listing.Category', verbose_name='Категория')),
                ('subcategories', models.ManyToManyField(to='listing.SubCategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Школы',
                'verbose_name_plural': 'Школа',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', models.CharField(max_length=255, verbose_name='Описание курса')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на страницу курса')),
                ('price', models.IntegerField(verbose_name='Базовая стоимость')),
                ('deferred_payment', models.BooleanField(default=True, verbose_name='Есть ли рассрочка?')),
                ('discount', models.BooleanField(default=False, verbose_name='Есть ли скидка?')),
                ('discount_amount', models.IntegerField(blank=True, verbose_name='Размер скидки')),
                ('discounted_price', models.IntegerField(verbose_name='Стоимость по скидке')),
                ('duration', models.CharField(max_length=255, verbose_name='Продолжительность')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Дата старта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('categories', models.ManyToManyField(to='listing.Category', verbose_name='Категория')),
                ('course_format', models.ManyToManyField(to='listing.CourseFormat', verbose_name='Формат курса')),
                ('features', models.ManyToManyField(to='listing.Features', verbose_name='Особенности')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.school', verbose_name='Школа')),
                ('subcategories', models.ManyToManyField(blank=True, to='listing.SubCategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Школы',
                'verbose_name_plural': 'Школа',
            },
        ),
    ]
