# Generated by Django 3.1.5 on 2021-01-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_auto_20210129_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Размер скидки'),
        ),
    ]
