# Generated by Django 3.1.5 on 2021-01-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_auto_20210129_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Стоимость по скидке'),
        ),
    ]
