# Generated by Django 3.1.5 on 2021-03-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_category_flaticon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
    ]
