# Generated by Django 3.1.5 on 2021-05-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0019_auto_20210521_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
