# Generated by Django 3.1.5 on 2021-06-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0020_auto_20210528_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, max_length=255, null=True, verbose_name='Продолжительность'),
        ),
    ]
