# Generated by Django 3.1.5 on 2021-06-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0021_auto_20210602_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deferred_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Стоимость в рассрочку'),
        ),
    ]
