# Generated by Django 3.1.5 on 2021-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0022_course_deferred_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Особенности школы')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='features',
            field=models.ManyToManyField(blank=True, to='listing.SchoolFeatures', verbose_name='Особенности'),
        ),
    ]
