# Generated by Django 3.1.5 on 2021-06-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0023_auto_20210621_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Особенность курса', 'verbose_name_plural': 'Особенности курса'},
        ),
        migrations.AlterModelOptions(
            name='schoolfeatures',
            options={'verbose_name': 'Особенность школы', 'verbose_name_plural': 'Особенности школы'},
        ),
    ]
