# Generated by Django 3.1.5 on 2021-06-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0024_auto_20210622_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='partner_link',
            field=models.URLField(blank=True, null=True, verbose_name='Партнерская ссылка на страницу курса'),
        ),
        migrations.AddField(
            model_name='school',
            name='partner_link',
            field=models.URLField(blank=True, null=True, verbose_name='Партнерская ссылка на школу'),
        ),
    ]
